// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3roUgyT_ClY67g3Z7msRtLpL1Cai_4nY',
    appId: '1:831067867737:web:d7867e23645d1f75423f48',
    messagingSenderId: '831067867737',
    projectId: 'instagram-tut-833a0',
    authDomain: 'instagram-tut-833a0.firebaseapp.com',
    storageBucket: 'instagram-tut-833a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-gXG-gFGFf4xyCOgXyvltHt2vji9JeuY',
    appId: '1:831067867737:android:4de60960131c80a2423f48',
    messagingSenderId: '831067867737',
    projectId: 'instagram-tut-833a0',
    storageBucket: 'instagram-tut-833a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHlXTxyuEY3B8rjcEdMUXhn2xTV-KX1Mc',
    appId: '1:831067867737:ios:2ea01e96fd5f819c423f48',
    messagingSenderId: '831067867737',
    projectId: 'instagram-tut-833a0',
    storageBucket: 'instagram-tut-833a0.appspot.com',
    iosBundleId: 'com.example.instagramFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHlXTxyuEY3B8rjcEdMUXhn2xTV-KX1Mc',
    appId: '1:831067867737:ios:d190b84057ceddba423f48',
    messagingSenderId: '831067867737',
    projectId: 'instagram-tut-833a0',
    storageBucket: 'instagram-tut-833a0.appspot.com',
    iosBundleId: 'com.example.instagramFirebase.RunnerTests',
  );
}
